# syntax = docker/dockerfile:1

ARG NODE_VERSION=18.17.0

FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base as build

COPY package.json package-lock.json /app/

RUN yarn install

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD ["yarn", "dev" ]